// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered bio generator.
 *
 * - generateBio - A function that handles the bio generation process.
 * - GenerateBioInput - The input type for the generateBio function.
 * - GenerateBioOutput - The return type for the generateBio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBioInputSchema = z.object({
  name: z.string().describe('Your name'),
  profession: z.string().describe('Your current profession or job title'),
  skills: z.string().describe('A comma-separated list of your key skills'),
  experience: z.string().describe('A brief summary of your professional experience'),
  style: z
    .enum(['formal', 'casual', 'creative'])
    .default('casual')
    .describe('The desired style of the generated bio'),
});
export type GenerateBioInput = z.infer<typeof GenerateBioInputSchema>;

const GenerateBioOutputSchema = z.object({
  bio: z.string().describe('The generated professional bio.'),
});
export type GenerateBioOutput = z.infer<typeof GenerateBioOutputSchema>;

export async function generateBio(input: GenerateBioInput): Promise<GenerateBioOutput> {
  return generateBioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateBioPrompt',
  input: {schema: GenerateBioInputSchema},
  output: {schema: GenerateBioOutputSchema},
  prompt: `You are a professional bio writer. Generate a compelling bio based on the information provided.

Name: {{{name}}}
Profession: {{{profession}}}
Skills: {{{skills}}}
Experience: {{{experience}}}
Style: {{{style}}}

Write a bio in the {{{style}}} style. Make sure to include the provided skills and experience.

BIO:
`,
});

const generateBioFlow = ai.defineFlow(
  {
    name: 'generateBioFlow',
    inputSchema: GenerateBioInputSchema,
    outputSchema: GenerateBioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
